name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2710
          - arch: aarch64_cortex-a72
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa72
          - arch: aarch64_generic
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/layerscape/armv8_64b
          - arch: arm_arm1176jzf-s_vfp
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2708
          - arch: arm_arm926ej-s
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sam9x
          - arch: arm_cortex-a15_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ipq806x/generic
          - arch: arm_cortex-a5-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sama5
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2709
          - arch: arm_cortex-a8_vfpv3
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa8
          - arch: arm_cortex-a9
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic
          - arch: arm_cortex-a9_neon
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/imx/cortexa9
          - arch: arm_cortex-a9_vfpv3
            sdk_url_path: https://downloads.openwrt.org/releases/19.07.2/targets/mvebu/cortexa9
          - arch: arm_cortex-a9_vfpv3-d16
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9
          - arch: arm_fa526
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/gemini/generic
          - arch: arm_xscale
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/kirkwood/generic
          - arch: i386_pentium
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/legacy
          - arch: i386_pentium4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/generic
          - arch: mips64_octeon
            sdk_url_path: https://downloads.openwrt.org/releases/18.06.5/targets/octeon/generic
          - arch: mips64_octeonplus
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/octeon/generic
          - arch: mipsel_24kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ramips/mt7620
          - arch: mipsel_24kc_24kf
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/pistachio/generic
          - arch: mipsel_74kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/mips74k
          - arch: mipsel_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/generic
          - arch: mips_24kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ath79/generic
          - arch: x86_64
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/64
          # - arch: arc_arc700
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/arc770/generic
          #   sdk_name: -sdk-arc770-generic_
          # - arch: arc_archs
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/archs38/generic
          #   sdk_name: -sdk-archs38-generic_
          # - arch: armeb_xscale
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ixp4xx/generic
          #   sdk_name: -sdk-ixp4xx-generic_
          # - arch: powerpc_464fp
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/apm821xx/nand
          #   sdk_name: -sdk-apm821xx-nand_
          # - arch: powerpc_8540
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mpc85xx/generic
          #   sdk_name: -sdk-mpc85xx-generic_

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:release:cache:
            ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:cache:

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -yq gettext libncurses5-dev xsltproc zstd

      - name: Prepare SDK Home
        run: |
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Build package
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
        run: sh compile.sh

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "*.ipk"
