name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build ${{ matrix.package_format }} for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2710
          - arch: aarch64_cortex-a72
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa72
          - arch: aarch64_generic
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/layerscape/armv8_64b
          - arch: arm_arm1176jzf-s_vfp
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2708
          - arch: arm_arm926ej-s
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sam9x
          - arch: arm_cortex-a15_neon-vfpv4
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ipq806x/generic
          - arch: arm_cortex-a5-vfpv4
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sama5
          - arch: arm_cortex-a7_neon-vfpv4
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2709
          - arch: arm_cortex-a8_vfpv3
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa8
          - arch: arm_cortex-a9
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic
          - arch: arm_cortex-a9_neon
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/imx/cortexa9
          - arch: arm_cortex-a9_vfpv3
            package_format: ipk
            cache_scope: 19.07.2
            sdk_url_path: https://downloads.openwrt.org/releases/19.07.2/targets/mvebu/cortexa9
          - arch: arm_cortex-a9_vfpv3-d16
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9
          - arch: arm_fa526
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/gemini/generic
          - arch: arm_xscale
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/kirkwood/generic
          - arch: i386_pentium
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/legacy
          - arch: i386_pentium4
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/generic
          - arch: mips64_octeon
            package_format: ipk
            cache_scope: 18.06.5
            sdk_url_path: https://downloads.openwrt.org/releases/18.06.5/targets/octeon/generic
          - arch: mips64_octeonplus
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/octeon/generic
          - arch: mipsel_24kc
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ramips/mt7620
          - arch: mipsel_24kc_24kf
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/pistachio/generic
          - arch: mipsel_74kc
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/mips74k
          - arch: mipsel_mips32
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/generic
          - arch: mips_24kc
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ath79/generic
          - arch: x86_64
            package_format: apk
            cache_scope: snapshot
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/64
          - arch: aarch64_cortex-a53
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/bcm27xx/bcm2710
          - arch: aarch64_cortex-a72
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/mvebu/cortexa72
          - arch: aarch64_generic
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/layerscape/armv8_64b
          - arch: arm_arm1176jzf-s_vfp
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/bcm27xx/bcm2708
          - arch: arm_arm926ej-s
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/at91/sam9x
          - arch: arm_cortex-a15_neon-vfpv4
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/ipq806x/generic
          - arch: arm_cortex-a5-vfpv4
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/at91/sama5
          - arch: arm_cortex-a7_neon-vfpv4
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/bcm27xx/bcm2709
          - arch: arm_cortex-a8_vfpv3
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/sunxi/cortexa8
          - arch: arm_cortex-a9
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/bcm53xx/generic
          - arch: arm_cortex-a9_neon
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/imx/cortexa9
          - arch: arm_cortex-a9_vfpv3-d16
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/mvebu/cortexa9
          - arch: arm_fa526
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/gemini/generic
          - arch: arm_xscale
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/kirkwood/generic
          - arch: i386_pentium
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/x86/legacy
          - arch: i386_pentium4
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/x86/generic
          - arch: mips64_octeonplus
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/octeon/generic
          - arch: mipsel_24kc
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/ramips/mt7620
          - arch: mipsel_24kc_24kf
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/pistachio/generic
          - arch: mipsel_74kc
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/bcm47xx/mips74k
          - arch: mipsel_mips32
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/bcm47xx/generic
          - arch: mips_24kc
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/ath79/generic
          - arch: x86_64
            package_format: ipk
            cache_scope: 24.10.5
            sdk_url_path: https://downloads.openwrt.org/releases/24.10.5/targets/x86/64
          # - arch: arc_arc700
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/arc770/generic
          #   sdk_name: -sdk-arc770-generic_
          # - arch: arc_archs
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/archs38/generic
          #   sdk_name: -sdk-archs38-generic_
          # - arch: armeb_xscale
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ixp4xx/generic
          #   sdk_name: -sdk-ixp4xx-generic_
          # - arch: powerpc_464fp
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/apm821xx/nand
          #   sdk_name: -sdk-apm821xx-nand_
          # - arch: powerpc_8540
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mpc85xx/generic
          #   sdk_name: -sdk-mpc85xx-generic_

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache
      DEFAULT_OPENWRT_GOLANG_COMMIT: ${{ matrix.package_format == 'ipk' && '5065a2ff8f2a1bcba6e445397f33ac16d76b3ad3' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:${{ matrix.cache_scope }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:${{ matrix.cache_scope }}:release:cache:
            ${{ runner.os }}:openwrt-frp:${{ env.ARCH }}:${{ matrix.cache_scope }}:cache:

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -yq gettext libncurses5-dev nodejs npm xsltproc zstd

      - name: Prepare SDK Home
        run: |
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Build package
        env:
          OPENWRT_GOLANG_COMMIT: ${{ secrets.OPENWRT_GOLANG_COMMIT }}
        run: sh compile.sh

      - name: Normalize APK Asset Names
        if: matrix.package_format == 'apk'
        run: |
          for file in *.apk; do
            [ -e "$file" ] || continue
            mv "$file" "${file%.apk}-${ARCH}.apk"
          done

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.ipk
            *.apk
